#!/usr/bin/env python3
"""
Generate HiFi-GAN weight and bias memory files for Verilog simulation.

Usage:
    python generate_mem_files.py

Outputs:
    - weights.mem: Weight memory initialized with random values
    - biases.mem: Bias memory initialized with small values
"""

import numpy as np

# Fixed-point conversion helpers
def q2_14(value):
    """Convert float to Q2.14 format (16-bit)"""
    # Clamp to [-2, 2) range
    value = np.clip(value, -2.0, 1.99993896484375)
    fixed = int(value * (2**14))
    # Convert to 16-bit signed
    if fixed < 0:
        fixed = (1 << 16) + fixed
    return fixed & 0xFFFF

def q4_12(value):
    """Convert float to Q4.12 format (16-bit)"""
    # Clamp to [-8, 8) range
    value = np.clip(value, -8.0, 7.999755859375)
    fixed = int(value * (2**12))
    if fixed < 0:
        fixed = (1 << 16) + fixed
    return fixed & 0xFFFF

# PostNet configuration
POSTNET_LAYERS = [
    {'in_ch': 1, 'out_ch': 32, 'kernel': 5},   # Layer 0
    {'in_ch': 32, 'out_ch': 32, 'kernel': 5},  # Layer 1
    {'in_ch': 32, 'out_ch': 32, 'kernel': 5},  # Layer 2
    {'in_ch': 32, 'out_ch': 32, 'kernel': 5},  # Layer 3
    {'in_ch': 32, 'out_ch': 1, 'kernel': 5},   # Layer 4
]

def generate_weights():
    """Generate weight memory file"""
    with open('weights.mem', 'w') as f:
        f.write("// HiFi-GAN Weight Memory (Q2.14 format)\n")
        f.write("// Auto-generated by generate_mem_files.py\n\n")
        
        addr = 0
        for layer_idx, layer in enumerate(POSTNET_LAYERS):
            f.write(f"// Layer {layer_idx}: {layer['in_ch']}x{layer['out_ch']}x{layer['kernel']}\n")
            
            for out_ch in range(layer['out_ch']):
                for in_ch in range(layer['in_ch']):
                    for k in range(layer['kernel']):
                        # Generate random weight in range [-0.1, 0.1]
                        weight = np.random.uniform(-0.1, 0.1)
                        hex_val = q2_14(weight)
                        f.write(f"{hex_val:04X}  // @{addr:04X} L{layer_idx} out{out_ch} in{in_ch} k{k}\n")
                        addr += 1
            f.write("\n")
        
        print(f"Generated weights.mem with {addr} entries")

def generate_biases():
    """Generate bias memory file"""
    with open('biases.mem', 'w') as f:
        f.write("// HiFi-GAN Bias Memory (Q4.12 format)\n")
        f.write("// Auto-generated by generate_mem_files.py\n\n")
        
        addr = 0
        for layer_idx, layer in enumerate(POSTNET_LAYERS):
            f.write(f"// Layer {layer_idx}: {layer['out_ch']} biases\n")
            
            for out_ch in range(layer['out_ch']):
                # Generate small random bias in range [-0.01, 0.01]
                bias = np.random.uniform(-0.01, 0.01)
                hex_val = q4_12(bias)
                f.write(f"{hex_val:04X}  // @{addr:02X} L{layer_idx} ch{out_ch}\n")
                addr += 1
            f.write("\n")
        
        print(f"Generated biases.mem with {addr} entries")

if __name__ == "__main__":
    np.random.seed(42)  # Reproducible random values
    generate_weights()
    generate_biases()
    print("\nMemory files generated successfully!")
    print("Use these files for Verilog simulation with $readmemh")
